site:
  name: Nein zur Bezahlkarte Karlsruhe
  site: 'https://nein-zur-bezahlkarte-karlsruhe.de'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: Nein zur Bezahlkarte Karlsruhe
    template: '%s – Nein zur Bezahlkarte Karlsruhe'
  description: "Wir engagieren uns für Geflüchtete und gegen die Einführung der Bezahlkarte in Karlsruhe"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Nein zur Bezahlkarte Karlsruhe
    images:
      - url: '~/assets/images/logo.webp'
        width: 1200
        height: 628
    type: website

i18n:
  language: de
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: 'blog/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4
  eventBlog:
    isEnabled: true
    postsPerPage: 6

    event:
      isEnabled: true
      permalink: 'termine/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'termine'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'termine/category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'termine/tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4
  
analytics:
  vendors:

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
